name: Submit Predictions
description: Submit your glycan structure predictions
title: "[Submission] YOUR_USERNAME"
labels: ["submission"]
body:
  - type: input
    id: username
    attributes:
      label: GitHub Username or Model Name
      description: Your GitHub username or model name (will be used for leaderboard)
      placeholder: "your_username"
    validations:
      required: true
  - type: textarea
    id: public_files
    attributes:
      label: Public Test Predictions
      description: Attach your PUBLIC test CSV files (these will be automatically evaluated)
      placeholder: "Drag your public test CSV files here..."
    validations:
      required: false
  - type: textarea
    id: private_files
    attributes:
      label: Private Test Predictions
      description: Attach your PRIVATE test CSV files (these will be stored for final evaluation)
      placeholder: "Drag your private test CSV files here..."
    validations:
      required: false
  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      options:
        - label: I have validated my files using `python validation/check_format.py`
          required: true
        - label: My CSV files follow the required format (m/z, RT, charge, top1_pred columns)
          required: true